import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import {ClerkProvider} from "@clerk/nextjs";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Board.',
  description: 'Generated by create next app',
    icons: {
      icon: '/icon.png',
    }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <ClerkProvider>
          <html lang="en">
          <head>
              <link rel={'icon'} href={'/img_8.png'}/>
              <title>Board.</title>
          </head>
            <body className={inter.className}>{children}</body>
          </html>
      </ClerkProvider>

  )
}
