import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import {ClerkProvider} from "@clerk/nextjs";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Board.',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <ClerkProvider>
          <link rel="icon" href="/icons8-b-100.png" />
          <html lang="en">
        <body className={inter.className}>{children}</body>
        </html>
      </ClerkProvider>

  )
}
